### PR TITLE
Changes in nothing

### PR DESCRIPTION
**Pull request by fremad**
I think that I have changed the project for the better :)  :+1:

### CODE REVIEW

**Comment by LarsHjerrild** [comment]
Have you checked that your spelling is correct or are you just guessing that it will be correct ?

**Comment by fremad** [comment]
I am pretty sure that it is but it is a slight problem that there are no reviewers to this code !!!! What do you think ???

**Comment by LarsHjerrild** [comment]
I will request a review from someone !!!!

**Comment by fremad** [comment]
<h1> This is a feature!! <h1>
<p> however poorly it is written ! <p>

**Comment by LarsHjerrild** [comment]
Ahh freck Ill let it in ! :1st_place_medal:

**Pull request merged**
